{ pkgs, lib, config, ... }:

let
  # Define dotfiles directory relative to the flake root
  dotfiles = ../../dotfiles;
in
{
  # Home Manager dotfile management
  # The primary way to manage plain files is through 'home.file'.
  home.file = {
    # Hyprland configuration
    ".config/hypr/basic.conf".source = "${dotfiles}/hyprland_basic.conf";

    ".config/waybar" = {
      source = "${dotfiles}/waybar";
      recursive = true;
    };

    ".config/hypr/screenshots" = {
      source = "${dotfiles}/hypr/screenshots";
      recursive = true;
    };

    ".config/hypr/hypr_gamemode.sh".source = "${dotfiles}/hypr/hypr_gamemode.sh";
    ".config/wofi/style.css".source = "${dotfiles}/hypr/wofi.css";
    ".config/hypr/hyprpaper.conf".source = "${dotfiles}/hypr/hyprpaper.conf";

    # Application launchers
    ".local/share/applications/Bemoji.desktop".source = "${dotfiles}/Bemoji.desktop";

    # Terminal configuration
    ".tmux.conf".source = "${dotfiles}/tmuxconf";

    # Git configuration
    ".gitconfig".source = "${dotfiles}/gitconfig";

    # KDE/Yakuake configuration
    ".config/autostart/org.kde.yakuake.desktop".source = "${dotfiles}/yakuake_autostart";
    ".config/autostart/nm-applet.desktop".source = "${dotfiles}/nm-applet_autostart";
    ".config/yakuakerc".source = "${dotfiles}/yakuakerc";

    # Utility scripts
    ".local/bin/ls-iommu".source = "${dotfiles}/ls-iommu";
    ".local/bin/ls-usb".source = "${dotfiles}/ls-usb";

    # Game configuration (Elite Dangerous bindings)
    ".local/share/Steam/steamapps/compatdata/359320/pfx/drive_c/users/steamuser/Local Settings/Application Data/Frontier Developments/Elite Dangerous/Options/Bindings/Custom.4.1.binds".source = "${dotfiles}/Elite_Dangerous_4.1";

    # Note: virt XML is autogenerated and stored in /var/lib/libvirt/qemu/win10-vfio.xml
    # Run this once the machine has been started once: `sudo virsh net-autostart default`
  };

  # Configure dconf for virt-manager
  dconf.settings = {
    "org/virt-manager/virt-manager/connections" = {
      autoconnect = ["qemu:///system"];
      uris = ["qemu:///system"];
    };
  };
}
