{ pkgs, lib, ... }:

{
  # Configure dconf for virt-manager
  dconf.settings = {
    "org/virt-manager/virt-manager/connections" = {
      autoconnect = ["qemu:///system"];
      uris = ["qemu:///system"];
    };
  };

  # Note: virt XML is autogenerated and stored in /var/lib/libvirt/qemu/win10-vfio.xml
  # Run this once the machine has been started once: `sudo virsh net-autostart default`
}
